### ISSUE TITLE
Error get current location

### ISSUE THREAD

**Issue by oliveiraCode** [MSlaski/MyWeatherApp#1]
The app doesn't get the current location, it's always Manhattan. 

![image](https://user-images.githubusercontent.com/30808315/51265134-0dd6be00-1986-11e9-97bb-c340b15ac6c1.png)

**Comment by MSlaski** [comment]
Are you using simulator or real device? If you are using simulator try to change simulator's location at debug area

**Comment by MSlaski** [comment]
When you are testing app at Simulator and you provide Coords for custom location you have to open Maps App first, then Simulator will read that location and after that it will refresh this app UI. I tested it at real Device and all works perfect
